services:
  - type: web
    name: be-rao
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: be-rao-db
          property: connectionString

databases:
  - name: be-rao-db
    plan: free
